# Generated by Django 3.2.3 on 2024-11-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=500)),
                ('client_image', models.ImageField(upload_to='Tasks/Clients')),
                ('task_image', models.ImageField(upload_to='Tasks/OurImages')),
            ],
        ),
    ]
