# Generated by Django 3.2.3 on 2024-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_auto_20241129_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
